#!/usr/bin/env bash
#transfers a file from our client to a server

# Check if enough arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: ./script.sh PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Store arguments in variables for better readability
FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Use scp command to transfer the file
if [ -z "$PATH_TO_SSH_KEY" ]; then
    scp -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$IP":~/
else
    scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$IP":~/
fi

