#!/usr/bin/env bash
# Update the system packages
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Get the hostname of the current server
name=$(hostname)

# Create a simple HTML page
echo "<h1>Welcome to $name</h1>" > /var/www/html/index.html

# Create a simple error page
echo "<h1>Error 404 - Page Not Found</h1>" > /var/www/html/error_404.html

# Define the Nginx configuration
config="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    add_header X-Served-By $name always;

    root /var/www/html;

    index index.html;

    server_name proto-byte.tech;

    error_page 404 /error_404.html;

    location = /error_404.html {
        root /var/www/html;
        internal;
    }

    location /redirect_me {
        return 301 https://www.nginx.com/blog/creating-nginx-rewrite-rules/;
    }
}"

# Write the configuration to the Nginx sites-available directory
echo "$config" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
