#!/usr/bin/env bash
# Update the system packages
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

echo "
frontend www
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 485409-web-01 52.201.220.108:80 check
    server 485409-web-02 10.0.0.2:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the changes
sudo service haproxy restart

